<a href="https://colab.research.google.com/github/putrimaharani355/Data-Scientist-/blob/main/Company_Coaching_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Dataset CCV 4 - Data Cleaning.csv')

In [ ]:
df.head()

,id_order,id_produk,nama_produk,kategori_produk,tanggal_pembelian,kuantitas,total_harga,PPN,bayar_cash,metode_bayar
0,1,3,hic1000 vitamin lemon,beverages,2023-04-09,5.0,39452.0,0.1,1.0,cash
1,2,6,nutrive benecol,special needs,2023-05-01,1.0,33732.0,0.1,1.0,cash
2,3,6,nutrive benecol,special needs,2023-03-22,NaN,23035.0,0.1,1.0,cash
3,4,5,prenagen lova,woman,2023-04-12,2.0,31237.0,0.1,0.0,link aja
4,5,6,nutrive benecol,special needs,2023-01-20,5.0,32000.0,0.1,1.0,cash

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1712 entries, 0 to 1711
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_order           1712 non-null   int64
 1   id_produk          1712 non-null   int64
 2   nama_produk        1712 non-null   object
 3   kategori_produk    1712 non-null   object
 4   tanggal_pembelian  1712 non-null   object
 5   kuantitas          1692 non-null   float64
 6   total_harga        1692 non-null   float64
 7   PPN                1711 non-null   float64
 8   bayar_cash         1704 non-null   float64
 9   metode_bayar       1712 non-null   object
dtypes: float64(4), int64(2), object(4)
memory usage: 133.9+ KB

In [ ]:
df.describe()

,id_order,id_produk,kuantitas,total_harga,PPN,bayar_cash
count,1712.000000,1712.000000,1692.000000,1692.000000,1.711000e+03,1704.000000
mean,856.500000,3.442173,3.947991,43542.563830,1.000000e-01,0.601526
std,494.356147,1.740345,1.983287,14971.400255,3.178943e-15,0.489728
min,1.000000,1.000000,1.000000,17264.000000,1.000000e-01,0.000000
25%,428.750000,2.000000,2.000000,30973.750000,1.000000e-01,0.000000
50%,856.500000,3.000000,4.000000,43339.500000,1.000000e-01,1.000000
75%,1284.250000,5.000000,6.000000,56225.750000,1.000000e-01,1.000000
max,1712.000000,6.000000,7.000000,69824.000000,1.000000e-01,1.000000

## Missing Values

In [ ]:
df = df.fillna(
    {'kuantitas':float(f'{df.kuantitas.median()}'),
     'total_harga':float(f'{df.total_harga.median()}'),
     'PPN': 0.1}

)

In [ ]:
df = df.drop(columns='bayar_cash')
df.isna().sum()

id_order             0
id_produk            0
nama_produk          0
kategori_produk      0
tanggal_pembelian    0
kuantitas            0
total_harga          0
PPN                  0
metode_bayar         0
dtype: int64

In [ ]:
df = df.astype({
    'tanggal_pembelian': 'datetime64[ns]',
    'kategori_produk': 'category',
    'kuantitas': 'int64',
    'total_harga': 'int64',
})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1712 entries, 0 to 1711
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_order           1712 non-null   int64
 1   id_produk          1712 non-null   int64
 2   nama_produk        1712 non-null   object
 3   kategori_produk    1712 non-null   category
 4   tanggal_pembelian  1712 non-null   datetime64[ns]
 5   kuantitas          1712 non-null   int64
 6   total_harga        1712 non-null   int64
 7   PPN                1712 non-null   float64
 8   metode_bayar       1712 non-null   object
dtypes: category(1), datetime64[ns](1), float64(1), int64(4), object(2)
memory usage: 109.0+ KB